# Identificadores del proyecto en SonarCloud
sonar.projectKey=wzwzDev_NextQuizAI
sonar.organization=wzwzdev

# Fuente del código
sonar.sources=src
sonar.sourceEncoding=UTF-8


# Opcional: excluir carpetas no necesariasv
sonar.exclusions=**/node_modules/**,**/*.test.ts,**/__tests__/**,**/generated/**,**/generated/**/*,src/generated/**,src/generated/**/*,src/generated/prisma/runtime/edge-esm.js
# Cobertura de código (si usas Jest + cobertura)
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=src/app/**/page.tsx,src/app/layout.tsx,src/components/**,src/generated/**,src/lib/**,src/server/ai/experimental/**,src/server/core/auth.ts,src/server/ai/openaiClient.ts,src/server/question-generation/generateQuestions.ts,src/server/**/index.ts

# URL de SonarCloud
sonar.host.url=https://sonarcloud.io

# El token de autenticación va en los secrets de GitHub, no se pone aquí directamente
sonar.token=${SONAR_TOKEN}
